# Generated by Django 6.0 on 2025-12-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['title'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='active',
            field=models.BooleanField(default=True, verbose_name='აქტიური'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='შექმნის თარიღი'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='იმეილი'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='განახლების თარიღი'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='website',
            field=models.URLField(null=True, unique=True, verbose_name='ვებსაიტი'),
        ),
    ]
