# Generated by Django 6.0 on 2025-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_documents_blogpost_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
