# Generated by Django 5.2.7 on 2025-10-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='სათაური')),
                ('text', models.TextField(verbose_name='ტექსტი')),
                ('active', models.BooleanField(default=True, verbose_name='აქტიურია')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შექმნით დრო')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლების დრო')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='იმეილი')),
                ('website', models.URLField(null=True, verbose_name='ვებსაიტი')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'ordering': ['title'],
                'unique_together': {('title', 'text')},
            },
        ),
    ]
