# Generated by Django 5.2.7 on 2025-10-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['title'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
