# Generated by Django 5.2.7 on 2025-10-28 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('title', 'text')},
        ),
    ]
