# Generated by Django 5.2.7 on 2025-10-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='active',
            field=models.BooleanField(default=True, verbose_name='აქტიურია'),
        ),
    ]
