# Generated by Django 6.0 on 2026-01-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='სათაური')),
                ('text', models.TextField(verbose_name='ტექსტი')),
                ('active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლების თარიღი')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='იმეილი')),
                ('website', models.URLField(null=True, unique=True, verbose_name='ვებსაიტი')),
                ('documents', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BlogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
            options={
                'verbose_name': 'BlogImage',
                'verbose_name_plural': 'BlogImages',
                'ordering': ['blog'],
            },
        ),
    ]
