# Generated by Django 5.2.8 on 2026-01-10 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_email_blog_authors_alter_author_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerImage', models.ImageField(blank=True, null=True, upload_to='./bannerImages/')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner_image', to='blog.blog')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
                'ordering': ['blog'],
            },
        ),
    ]
