# Generated by Django 5.2.8 on 2026-01-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_bannerimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='blog',
        ),
    ]
