# Generated by Django 5.2.8 on 2026-01-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_author_id_alter_bannerimages_id_alter_blog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='authors',
            field=models.ManyToManyField(related_name='blogs', to='blog.author', verbose_name='ავტორები'),
        ),
    ]
