# Generated by Django 5.2.8 on 2026-01-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='დაბადების თარიღი'),
        ),
    ]
